#!/usr/bin/env bash

## Copyright (C) 2023 [Github] <https://github.com/adeleyemosh>

#  __  __  ____   _____ _    _
# |  \/  |/ __ \ / ____| |  | |
# | \  / | |  | | (___ | |__| |
# | |\/| | |  | |\___ \|  __  |
# | |  | | |__| |____) | |  | |
# |_|  |_|\____/|_____/|_|  |_|
##
## Script to manage speaker volume

# Icons directory
ICON_DIR="$HOME/.config/qtile/icons/dunst/"
notify_cmd='dunstify -u low -h string:x-dunst-stack-tag:obvolume'

# Get Volume
get_volume() {
	echo "`pulsemixer --get-volume | cut -d' ' -f1`"
}

# Get icons
get_icon() {
	current="$(get_volume)"
	if [[ "$current" -eq "0" ]]; then
		icon="${ICON_DIR}volume-mute.png"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		icon="${ICON_DIR}volume-low.png"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		icon="${ICON_DIR}volume-mid.png"
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		icon="${ICON_DIR}volume-high.png"
	fi
}

# Notify
notify_user() {
	${notify_cmd} -i "$icon" "Volume : $(get_volume)%"
}

# Increase Volume
inc_volume() {
	[[ `pulsemixer --get-mute` == 1 ]] && pulsemixer --unmute
	pulsemixer --max-volume 100 --change-volume +5 && get_icon && notify_user
}

# Decrease Volume
dec_volume() {
	[[ `pulsemixer --get-mute` == 1 ]] && pulsemixer --unmute
	pulsemixer --max-volume 100 --change-volume -5 && get_icon && notify_user
}

# Toggle Mute
toggle_mute() {
	if [[ `pulsemixer --get-mute` == 0 ]]; then
		pulsemixer --toggle-mute && ${notify_cmd} -i "${ICON_DIR}volume-mute.png" "Mute"
	else
		pulsemixer --toggle-mute && get_icon && ${notify_cmd} -i "$icon" "Unmute"
	fi
}

# Toggle Mic
toggle_mic() {
	ID="`pulsemixer --list-sources | grep 'Default' | cut -d',' -f1 | cut -d' ' -f3`"
	if [[ `pulsemixer --id $ID --get-mute` == 0 ]]; then
		pulsemixer --id ${ID} --toggle-mute && ${notify_cmd} -i "${ICON_DIR}microphone-mute.png" "Microphone Switched OFF"
	else
		pulsemixer --id ${ID} --toggle-mute && ${notify_cmd} -i "${ICON_DIR}microphone.png" "Microphone Switched ON"
	fi
}

# Execute accordingly
if [[ -x `which pulsemixer` ]]; then
	if [[ "$1" == "--get" ]]; then
		get_volume
	elif [[ "$1" == "--inc" ]]; then
		inc_volume
	elif [[ "$1" == "--dec" ]]; then
		dec_volume
	elif [[ "$1" == "--toggle" ]]; then
		toggle_mute
	elif [[ "$1" == "--toggle-mic" ]]; then
		toggle_mic
	else
		echo $(get_volume)%
	fi
else
	${notify_cmd} "'pulsemixer' is not installed."
fi
