#!/usr/bin/env bash

## Copyright (C) 2023 Moshood Adeleye <adeleyemosh@gmail.com>

# qtile directory
DIR="$HOME/.config/qtile"

# Terminate if picom is already running
killall -q picom

# Wait until the processes have been shut down
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done

# Launch picom
picom --config "$DIR"/picom.conf &
