#!/bin/bash

## Copyright (C) 2023 [Github] <https://github.com/adeleyemosh>
#  __  __  ____   _____ _    _
# |  \/  |/ __ \ / ____| |  | |
# | \  / | |  | | (___ | |__| |
# | |\/| | |  | |\___ \|  __  |
# | |  | | |__| |____) | |  | |
# |_|  |_|\____/|_____/|_|  |_|
##
## Autostart Programs

# Qtile directory
qdir="$HOME/.config/qtile"
xdir="$HOME/.config/xsettingsd"

# Kill already running processes
processes=("xsettingsd" "ksuperkey")

for process in "${processes[@]}"; do
    if pidof $process > /dev/null; then
        killall -9 $process
    fi
done

# Configure display settings
xrandr --output eDP-1 --primary --mode 3200x1800 --pos 0x0 --rotate normal

# Start conky for system overview
(conky -c "$qdir/scripts/system-overview") &

# Start gnome-polkit if not running
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Launch xsettingsd daemon
xsettingsd --config="$qdir/xsettingsd" &

# Start xfce-polkit if not running
if ! pidof xfce-polkit > /dev/null; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Enable power management
xfce4-power-manager &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Set the cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
"$qdir/themes/wallpaper.sh"

# Launch notification daemon
"$qdir/scripts/qtile_dunst" &

# Launch polybar
"$qdir/scripts/qtile_bar" &

# Launch compositor
"$qdir/scripts/qtile_comp" &

# Launch whatsapp
# "$qdir/scripts/launch-whatsapp.sh" &

# Start
exec variety &
exec barrier &
exec kdeconnect &
