#!/usr/bin/env bash

## Copyright (C) 2023 [Github] <https://github.com/adeleyemosh>
#  __  __  ____   _____ _    _
# |  \/  |/ __ \ / ____| |  | |
# | \  / | |  | | (___ | |__| |
# | |\/| | |  | |\___ \|  __  |
# | |  | | |__| |____) | |  | |
# |_|  |_|\____/|_____/|_|  |_|

# Import Current Theme
DIR="$HOME/.config/qtile"
STYLE="amaterasu"
RASI="$DIR/themes/$STYLE/rofi/launcher.rasi"

# Run
rofi \
    -show drun \
	-kb-cancel Alt-F1 \
	-theme ${RASI}
