#!/usr/bin/env bash

## Copyright (C) 2023 [Github] <https://github.com/adeleyemosh>
#  __  __  ____   _____ _    _
# |  \/  |/ __ \ / ____| |  | |
# | \  / | |  | | (___ | |__| |
# | |\/| | |  | |\___ \|  __  |
# | |  | | |__| |____) | |  | |
# |_|  |_|\____/|_____/|_|  |_|

# Import Current Theme
DIR="$HOME/.config/qtile"
STYLE="amaterasu"
RASI="$DIR/themes/$STYLE/rofi/themes.rasi"

# List Available Themes
THEMES=(`cd $DIR/themes && ls -d */ | cut -d '/' -f1`)

# Theme Elements
prompt="Themes"
mesg="<b>Available Themes</b> : `cd $DIR/themes && ls -d */ | cut -d '/' -f1 | wc -l`"

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-sep '|' \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo ${THEMES[@]} | sed 's/ /|/g' | sed 's/$/|/' | sed 's/^/Random||/' | rofi_cmd
}

# Apply Theme
apply_theme() {
	selected="`run_rofi`"
	current="`cat $DIR/themes/.current`"

	for theme in "${THEMES[@]}"; do
		if [[ -z "$selected" ]]; then
			break
		elif [[ "$selected" == "$theme" ]]; then
			"$DIR"/themes/"$theme"/apply.sh
			break
		elif [[ "$selected" == 'Random' ]]; then
			"$DIR"/themes/"$current"/random.sh
			break
		fi
	done
}

apply_theme && exit 0
