#!/usr/bin/env bash
## Copyright (C) 2023 [Github] <https://github.com/adeleyemosh>
#  __  __  ____   _____ _    _
# |  \/  |/ __ \ / ____| |  | |
# | \  / | |  | | (___ | |__| |
# | |\/| | |  | |\___ \|  __  |
# | |  | | |__| |____) | |  | |
# |_|  |_|\____/|_____/|_|  |_|

# Import Current Theme
DIR="$HOME/.config/qtile"
STYLE="amaterasu"
RASI="$DIR/themes/$STYLE/rofi/askpass.rasi"

# Rofi text dialog to get password
rofi -dmenu \
     -password \
     -i \
     -p "Root" \
     -theme ${RASI}
