#!/usr/bin/env bash

## Copyright (C) 2023 Moshood Adeleye <adeleyemosh@gmail.com>

# Import Current Theme
DIR="$HOME/.config/qtile"
STYLE="darkred"
RASI="$DIR/themes/$STYLE/rofi/launcher.rasi"

# Run
rofi \
    -show drun \
	-kb-cancel Alt-F1 \
	-theme ${RASI}
