## Copyright (C) 2023 Moshood Adeleye <adeleyemosh@gmail.com>

#  __  __  ____   _____ _    _
# |  \/  |/ __ \ / ____| |  | |
# | \  / | |  | | (___ | |__| |
# | |\/| | |  | |\___ \|  __  |
# | |  | | |__| |____) | |  | |
# |_|  |_|\____/|_____/|_|  |_|

#####################################################

[module/sep]
type = custom/text
content = -

content-background = ${color.background}
content-foreground = ${color.background}

[module/dot]
type = custom/text
content = 

content-background = ${color.background}
content-foreground = ${color.background-alt}
content-padding = 2


