#!/bin/bash

## Files and config
FILE="$HOME/.cache/eww_launch.tama"
CFG="$HOME/.config/eww/desktop-widget-theme/tama"
EWW="$(which eww)"

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
    $EWW daemon
    sleep 1
fi

## Open all defined windows in the tama theme
run_eww() {
    $EWW --config "$CFG" open-many \
        smol_calendar \
        weather_side \
        player_side \
        time_side \
        sliders_side \
        sys_side \
        search_full \
        power_full \
        reboot_full \
        lock_full \
        suspend_full \
        logout_full \
        close_full \
        player \
        profile \
        weather \
        home_dir \
        quote \
        screenshot \
        vpn-icon \
        disturb-icon \
        blur_full
}

## Toggle widgets
if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    run_eww
else
    $EWW --config "$CFG" close \
        smol_calendar weather_side player_side time_side sliders_side sys_side \
        search_full power_full reboot_full lock_full suspend_full logout_full close_full \
        player profile weather home_dir quote screenshot vpn-icon disturb-icon blur_full
    rm "$FILE"
fi
